# Generated by Django 3.1.6 on 2021-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thai', models.CharField(max_length=20)),
                ('phonetic', models.CharField(max_length=20)),
                ('meaning', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('phonetic', 'meaning'),
            },
        ),
    ]
