# Generated by Django 3.1.6 on 2021-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
